import {
  Folder,
  Briefcase,
  Rocket,
  Target,
  TrendingUp,
  Users,
  Building2,
  Megaphone,
  Code2,
  Palette,
  Lightbulb,
  Heart,
  Star,
  Zap,
  Shield,
  BookOpen,
  Coffee,
  Globe,
  Package,
  Truck,
  DollarSign,
  BarChart3,
  Calendar,
  ClipboardList,
  Cpu,
  Database,
  Flag,
  GitBranch,
  Hammer,
  Headphones,
  Layers,
  LifeBuoy,
  Sparkles,
  type LucideIcon,
} from "lucide-react";

export const SECTION_ICONS: { key: string; icon: LucideIcon; label: string }[] = [
  { key: "folder", icon: Folder, label: "Folder" },
  { key: "briefcase", icon: Briefcase, label: "Briefcase" },
  { key: "rocket", icon: Rocket, label: "Rocket" },
  { key: "target", icon: Target, label: "Target" },
  { key: "trending-up", icon: TrendingUp, label: "Growth" },
  { key: "users", icon: Users, label: "People" },
  { key: "building", icon: Building2, label: "Building" },
  { key: "megaphone", icon: Megaphone, label: "Marketing" },
  { key: "code", icon: Code2, label: "Engineering" },
  { key: "palette", icon: Palette, label: "Design" },
  { key: "lightbulb", icon: Lightbulb, label: "Ideas" },
  { key: "heart", icon: Heart, label: "Heart" },
  { key: "star", icon: Star, label: "Star" },
  { key: "zap", icon: Zap, label: "Zap" },
  { key: "shield", icon: Shield, label: "Security" },
  { key: "book", icon: BookOpen, label: "Knowledge" },
  { key: "coffee", icon: Coffee, label: "Coffee" },
  { key: "globe", icon: Globe, label: "Globe" },
  { key: "package", icon: Package, label: "Package" },
  { key: "truck", icon: Truck, label: "Delivery" },
  { key: "dollar", icon: DollarSign, label: "Sales" },
  { key: "chart", icon: BarChart3, label: "Analytics" },
  { key: "calendar", icon: Calendar, label: "Calendar" },
  { key: "clipboard", icon: ClipboardList, label: "Ops" },
  { key: "cpu", icon: Cpu, label: "Tech" },
  { key: "database", icon: Database, label: "Data" },
  { key: "flag", icon: Flag, label: "Flag" },
  { key: "git", icon: GitBranch, label: "Branch" },
  { key: "hammer", icon: Hammer, label: "Build" },
  { key: "headphones", icon: Headphones, label: "Support" },
  { key: "layers", icon: Layers, label: "Layers" },
  { key: "life-buoy", icon: LifeBuoy, label: "Help" },
  { key: "sparkles", icon: Sparkles, label: "Sparkles" },
];

export function getSectionIcon(key: string | null | undefined): LucideIcon {
  return SECTION_ICONS.find((i) => i.key === key)?.icon ?? Folder;
}
