/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as DocsSelfHostRouteImport } from './routes/docs.self-host'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppNotesRouteImport } from './routes/app.notes'
import { Route as AppMyTasksRouteImport } from './routes/app.my-tasks'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppSettingsIndexRouteImport } from './routes/app.settings.index'
import { Route as AppSettingsResourcesRouteImport } from './routes/app.settings.resources'
import { Route as AppSettingsProfileRouteImport } from './routes/app.settings.profile'
import { Route as AppSettingsMembersRouteImport } from './routes/app.settings.members'
import { Route as AppSettingsFieldsRouteImport } from './routes/app.settings.fields'
import { Route as AppSettingsDataRouteImport } from './routes/app.settings.data'
import { Route as AppSettingsDangerRouteImport } from './routes/app.settings.danger'
import { Route as AppSettingsAutomationsRouteImport } from './routes/app.settings.automations'
import { Route as AppSettingsAiRouteImport } from './routes/app.settings.ai'
import { Route as AppPProjectIdRouteImport } from './routes/app.p.$projectId'
import { Route as AppMeetingsMeetingIdRouteImport } from './routes/app.meetings.$meetingId'
import { Route as AppPProjectIdSprintsRouteImport } from './routes/app.p.$projectId.sprints'
import { Route as AppPProjectIdSettingsRouteImport } from './routes/app.p.$projectId.settings'
import { Route as AppPProjectIdMilestonesRouteImport } from './routes/app.p.$projectId.milestones'
import { Route as AppPProjectIdHealthRouteImport } from './routes/app.p.$projectId.health'
import { Route as AppPProjectIdFinancialsRouteImport } from './routes/app.p.$projectId.financials'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSelfHostRoute = DocsSelfHostRouteImport.update({
  id: '/docs/self-host',
  path: '/docs/self-host',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTasksRoute = AppMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsResourcesRoute = AppSettingsResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsFieldsRoute = AppSettingsFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDataRoute = AppSettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDangerRoute = AppSettingsDangerRouteImport.update({
  id: '/danger',
  path: '/danger',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAutomationsRoute = AppSettingsAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppPProjectIdRoute = AppPProjectIdRouteImport.update({
  id: '/p/$projectId',
  path: '/p/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsMeetingIdRoute = AppMeetingsMeetingIdRouteImport.update({
  id: '/$meetingId',
  path: '/$meetingId',
  getParentRoute: () => AppMeetingsRoute,
} as any)
const AppPProjectIdSprintsRoute = AppPProjectIdSprintsRouteImport.update({
  id: '/sprints',
  path: '/sprints',
  getParentRoute: () => AppPProjectIdRoute,
} as any)
const AppPProjectIdSettingsRoute = AppPProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppPProjectIdRoute,
} as any)
const AppPProjectIdMilestonesRoute = AppPProjectIdMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => AppPProjectIdRoute,
} as any)
const AppPProjectIdHealthRoute = AppPProjectIdHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppPProjectIdRoute,
} as any)
const AppPProjectIdFinancialsRoute = AppPProjectIdFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AppPProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/meetings': typeof AppMeetingsRouteWithChildren
  '/app/my-tasks': typeof AppMyTasksRoute
  '/app/notes': typeof AppNotesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/docs/self-host': typeof DocsSelfHostRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/p/$projectId': typeof AppPProjectIdRouteWithChildren
  '/app/settings/ai': typeof AppSettingsAiRoute
  '/app/settings/automations': typeof AppSettingsAutomationsRoute
  '/app/settings/danger': typeof AppSettingsDangerRoute
  '/app/settings/data': typeof AppSettingsDataRoute
  '/app/settings/fields': typeof AppSettingsFieldsRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/resources': typeof AppSettingsResourcesRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/p/$projectId/financials': typeof AppPProjectIdFinancialsRoute
  '/app/p/$projectId/health': typeof AppPProjectIdHealthRoute
  '/app/p/$projectId/milestones': typeof AppPProjectIdMilestonesRoute
  '/app/p/$projectId/settings': typeof AppPProjectIdSettingsRoute
  '/app/p/$projectId/sprints': typeof AppPProjectIdSprintsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/meetings': typeof AppMeetingsRouteWithChildren
  '/app/my-tasks': typeof AppMyTasksRoute
  '/app/notes': typeof AppNotesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/docs/self-host': typeof DocsSelfHostRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app': typeof AppIndexRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/p/$projectId': typeof AppPProjectIdRouteWithChildren
  '/app/settings/ai': typeof AppSettingsAiRoute
  '/app/settings/automations': typeof AppSettingsAutomationsRoute
  '/app/settings/danger': typeof AppSettingsDangerRoute
  '/app/settings/data': typeof AppSettingsDataRoute
  '/app/settings/fields': typeof AppSettingsFieldsRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/resources': typeof AppSettingsResourcesRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/p/$projectId/financials': typeof AppPProjectIdFinancialsRoute
  '/app/p/$projectId/health': typeof AppPProjectIdHealthRoute
  '/app/p/$projectId/milestones': typeof AppPProjectIdMilestonesRoute
  '/app/p/$projectId/settings': typeof AppPProjectIdSettingsRoute
  '/app/p/$projectId/sprints': typeof AppPProjectIdSprintsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/crm': typeof AppCrmRoute
  '/app/meetings': typeof AppMeetingsRouteWithChildren
  '/app/my-tasks': typeof AppMyTasksRoute
  '/app/notes': typeof AppNotesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRouteWithChildren
  '/docs/self-host': typeof DocsSelfHostRoute
  '/invite/$token': typeof InviteTokenRoute
  '/app/': typeof AppIndexRoute
  '/app/meetings/$meetingId': typeof AppMeetingsMeetingIdRoute
  '/app/p/$projectId': typeof AppPProjectIdRouteWithChildren
  '/app/settings/ai': typeof AppSettingsAiRoute
  '/app/settings/automations': typeof AppSettingsAutomationsRoute
  '/app/settings/danger': typeof AppSettingsDangerRoute
  '/app/settings/data': typeof AppSettingsDataRoute
  '/app/settings/fields': typeof AppSettingsFieldsRoute
  '/app/settings/members': typeof AppSettingsMembersRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/resources': typeof AppSettingsResourcesRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/p/$projectId/financials': typeof AppPProjectIdFinancialsRoute
  '/app/p/$projectId/health': typeof AppPProjectIdHealthRoute
  '/app/p/$projectId/milestones': typeof AppPProjectIdMilestonesRoute
  '/app/p/$projectId/settings': typeof AppPProjectIdSettingsRoute
  '/app/p/$projectId/sprints': typeof AppPProjectIdSprintsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/crm'
    | '/app/meetings'
    | '/app/my-tasks'
    | '/app/notes'
    | '/app/notifications'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/docs/self-host'
    | '/invite/$token'
    | '/app/'
    | '/app/meetings/$meetingId'
    | '/app/p/$projectId'
    | '/app/settings/ai'
    | '/app/settings/automations'
    | '/app/settings/danger'
    | '/app/settings/data'
    | '/app/settings/fields'
    | '/app/settings/members'
    | '/app/settings/profile'
    | '/app/settings/resources'
    | '/app/settings/'
    | '/app/p/$projectId/financials'
    | '/app/p/$projectId/health'
    | '/app/p/$projectId/milestones'
    | '/app/p/$projectId/settings'
    | '/app/p/$projectId/sprints'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/crm'
    | '/app/meetings'
    | '/app/my-tasks'
    | '/app/notes'
    | '/app/notifications'
    | '/app/profile'
    | '/app/search'
    | '/docs/self-host'
    | '/invite/$token'
    | '/app'
    | '/app/meetings/$meetingId'
    | '/app/p/$projectId'
    | '/app/settings/ai'
    | '/app/settings/automations'
    | '/app/settings/danger'
    | '/app/settings/data'
    | '/app/settings/fields'
    | '/app/settings/members'
    | '/app/settings/profile'
    | '/app/settings/resources'
    | '/app/settings'
    | '/app/p/$projectId/financials'
    | '/app/p/$projectId/health'
    | '/app/p/$projectId/milestones'
    | '/app/p/$projectId/settings'
    | '/app/p/$projectId/sprints'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/features'
    | '/how-it-works'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/app/crm'
    | '/app/meetings'
    | '/app/my-tasks'
    | '/app/notes'
    | '/app/notifications'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/docs/self-host'
    | '/invite/$token'
    | '/app/'
    | '/app/meetings/$meetingId'
    | '/app/p/$projectId'
    | '/app/settings/ai'
    | '/app/settings/automations'
    | '/app/settings/danger'
    | '/app/settings/data'
    | '/app/settings/fields'
    | '/app/settings/members'
    | '/app/settings/profile'
    | '/app/settings/resources'
    | '/app/settings/'
    | '/app/p/$projectId/financials'
    | '/app/p/$projectId/health'
    | '/app/p/$projectId/milestones'
    | '/app/p/$projectId/settings'
    | '/app/p/$projectId/sprints'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  DocsSelfHostRoute: typeof DocsSelfHostRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/self-host': {
      id: '/docs/self-host'
      path: '/docs/self-host'
      fullPath: '/docs/self-host'
      preLoaderRoute: typeof DocsSelfHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notes': {
      id: '/app/notes'
      path: '/notes'
      fullPath: '/app/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/my-tasks': {
      id: '/app/my-tasks'
      path: '/my-tasks'
      fullPath: '/app/my-tasks'
      preLoaderRoute: typeof AppMyTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/resources': {
      id: '/app/settings/resources'
      path: '/resources'
      fullPath: '/app/settings/resources'
      preLoaderRoute: typeof AppSettingsResourcesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/members': {
      id: '/app/settings/members'
      path: '/members'
      fullPath: '/app/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/fields': {
      id: '/app/settings/fields'
      path: '/fields'
      fullPath: '/app/settings/fields'
      preLoaderRoute: typeof AppSettingsFieldsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/data': {
      id: '/app/settings/data'
      path: '/data'
      fullPath: '/app/settings/data'
      preLoaderRoute: typeof AppSettingsDataRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/danger': {
      id: '/app/settings/danger'
      path: '/danger'
      fullPath: '/app/settings/danger'
      preLoaderRoute: typeof AppSettingsDangerRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/automations': {
      id: '/app/settings/automations'
      path: '/automations'
      fullPath: '/app/settings/automations'
      preLoaderRoute: typeof AppSettingsAutomationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/settings/ai': {
      id: '/app/settings/ai'
      path: '/ai'
      fullPath: '/app/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/app/p/$projectId': {
      id: '/app/p/$projectId'
      path: '/p/$projectId'
      fullPath: '/app/p/$projectId'
      preLoaderRoute: typeof AppPProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings/$meetingId': {
      id: '/app/meetings/$meetingId'
      path: '/$meetingId'
      fullPath: '/app/meetings/$meetingId'
      preLoaderRoute: typeof AppMeetingsMeetingIdRouteImport
      parentRoute: typeof AppMeetingsRoute
    }
    '/app/p/$projectId/sprints': {
      id: '/app/p/$projectId/sprints'
      path: '/sprints'
      fullPath: '/app/p/$projectId/sprints'
      preLoaderRoute: typeof AppPProjectIdSprintsRouteImport
      parentRoute: typeof AppPProjectIdRoute
    }
    '/app/p/$projectId/settings': {
      id: '/app/p/$projectId/settings'
      path: '/settings'
      fullPath: '/app/p/$projectId/settings'
      preLoaderRoute: typeof AppPProjectIdSettingsRouteImport
      parentRoute: typeof AppPProjectIdRoute
    }
    '/app/p/$projectId/milestones': {
      id: '/app/p/$projectId/milestones'
      path: '/milestones'
      fullPath: '/app/p/$projectId/milestones'
      preLoaderRoute: typeof AppPProjectIdMilestonesRouteImport
      parentRoute: typeof AppPProjectIdRoute
    }
    '/app/p/$projectId/health': {
      id: '/app/p/$projectId/health'
      path: '/health'
      fullPath: '/app/p/$projectId/health'
      preLoaderRoute: typeof AppPProjectIdHealthRouteImport
      parentRoute: typeof AppPProjectIdRoute
    }
    '/app/p/$projectId/financials': {
      id: '/app/p/$projectId/financials'
      path: '/financials'
      fullPath: '/app/p/$projectId/financials'
      preLoaderRoute: typeof AppPProjectIdFinancialsRouteImport
      parentRoute: typeof AppPProjectIdRoute
    }
  }
}

interface AppMeetingsRouteChildren {
  AppMeetingsMeetingIdRoute: typeof AppMeetingsMeetingIdRoute
}

const AppMeetingsRouteChildren: AppMeetingsRouteChildren = {
  AppMeetingsMeetingIdRoute: AppMeetingsMeetingIdRoute,
}

const AppMeetingsRouteWithChildren = AppMeetingsRoute._addFileChildren(
  AppMeetingsRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppSettingsAutomationsRoute: typeof AppSettingsAutomationsRoute
  AppSettingsDangerRoute: typeof AppSettingsDangerRoute
  AppSettingsDataRoute: typeof AppSettingsDataRoute
  AppSettingsFieldsRoute: typeof AppSettingsFieldsRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsResourcesRoute: typeof AppSettingsResourcesRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppSettingsAutomationsRoute: AppSettingsAutomationsRoute,
  AppSettingsDangerRoute: AppSettingsDangerRoute,
  AppSettingsDataRoute: AppSettingsDataRoute,
  AppSettingsFieldsRoute: AppSettingsFieldsRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsResourcesRoute: AppSettingsResourcesRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppPProjectIdRouteChildren {
  AppPProjectIdFinancialsRoute: typeof AppPProjectIdFinancialsRoute
  AppPProjectIdHealthRoute: typeof AppPProjectIdHealthRoute
  AppPProjectIdMilestonesRoute: typeof AppPProjectIdMilestonesRoute
  AppPProjectIdSettingsRoute: typeof AppPProjectIdSettingsRoute
  AppPProjectIdSprintsRoute: typeof AppPProjectIdSprintsRoute
}

const AppPProjectIdRouteChildren: AppPProjectIdRouteChildren = {
  AppPProjectIdFinancialsRoute: AppPProjectIdFinancialsRoute,
  AppPProjectIdHealthRoute: AppPProjectIdHealthRoute,
  AppPProjectIdMilestonesRoute: AppPProjectIdMilestonesRoute,
  AppPProjectIdSettingsRoute: AppPProjectIdSettingsRoute,
  AppPProjectIdSprintsRoute: AppPProjectIdSprintsRoute,
}

const AppPProjectIdRouteWithChildren = AppPProjectIdRoute._addFileChildren(
  AppPProjectIdRouteChildren,
)

interface AppRouteChildren {
  AppCrmRoute: typeof AppCrmRoute
  AppMeetingsRoute: typeof AppMeetingsRouteWithChildren
  AppMyTasksRoute: typeof AppMyTasksRoute
  AppNotesRoute: typeof AppNotesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppPProjectIdRoute: typeof AppPProjectIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppCrmRoute: AppCrmRoute,
  AppMeetingsRoute: AppMeetingsRouteWithChildren,
  AppMyTasksRoute: AppMyTasksRoute,
  AppNotesRoute: AppNotesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppPProjectIdRoute: AppPProjectIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  DocsSelfHostRoute: DocsSelfHostRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
